[project]
name = "np_notebooks"
version = "0.1.0"
description = "IPython notebooks for Mindscope Neuropixels workflows"
authors = [
    {name = "bjhardcastle", email = "ben.hardcastle@alleninstitute.org"}
]
license = {text = "MIT"}
requires-python = ">=3.11"

dependencies = [
    "jupyterlab>=3.6",
    "np-workflows>=1.4.0",
]